// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

// Account
type PreGoCrmUserC struct {
	// Account ID
	UsrID int32
	// Email
	UsrEmail string
	// Phone Number
	UsrPhone string
	// Username
	UsrUsername string
	// Password
	UsrPassword string
	// Creation Time
	UsrCreatedAt int32
	// Update Time
	UsrUpdatedAt int32
	// Creation IP
	UsrCreateIpAt string
	// Last Login Time
	UsrLastLoginAt int32
	// Last Login IP
	UsrLastLoginIpAt string
	// Login Times
	UsrLastLoginTimes int32
	// Status
	UsrStatus int32
}
